/// Exclude this file from repository
class Constants {
  static const String playerTheme =
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZmZlOGMyNGI1NDIyMzAwMDgwYjhjZTEiLCJ0ZWFtSWQiOiI1ZmZlOGMyNGI1NDIyMzAwMDgwYjhjZTAiLCJyb2xlSWQiOjEsImF1dGhUb2tlbiI6IjFmMmM5MjNlMzNmOWNkNWI3YmFkNDFmODhhNThmZTZhNTdhMzgxNDYiLCJpYXQiOjE2MTIwMzc1NTl9.YYbNgZoGKiHNiRBS-FOlLkaPlRp9LupE671s74qW37Q';
}
